version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: evergreen_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    volumes:
      - evergreen_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: evergreen_redis
    restart: always
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"

#  scheduler:
#      build: ../scheduler-service
#      ports: ["8080:8080"]

#  notification:
#      build: ../notification-service
#      ports: ["8081:8081"]

#  logger:
#      build: ../logger-service
#      ports: ["8082:8082"]

volumes:
  evergreen_pgdata:
