spring:
    application:
        name: scheduler-service

    config:
        import: optional:file:../infra/application-dev.yml

rabbitmq:
    exchange: notification.exchange
    queue: notification.queue
    routing-key: notification.key
